spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/teabag?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
  application:
    name: teabag
mybatis-plus:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: cn.th.teabag.entity
  configuration:
    map-underscore-to-camel-case: true

